# Site settings
title: Eric Frommelt
email: im@ericfrommelt.com
description: The professional and sometimes personal website of designer Eric Frommelt.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ericfrommelt.com" # the base hostname & protocol for your site
twitter_username: ericfrommelt
github_username:  ericfrommelt

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - gulpfile.js
  - _dev
  - node_modules
  - package.json
  - bower.json
  - Gemfile
  - Gemfile.lock

keep_files: []

collections:
  work:
    output: true
